
[tox]
minversion = 4.28.4
; The role repository cannot be packaged as a Python package.
skipsdist = true
; For environments with multiple FACTORS in their names,
; avoid using factors that are purely numeric with a dot (e.g., [23]\.[0-9]+),
; as they will be strictly matched and captured as `base_python`.
; Also avoid factors that start with py followed by numbers with
; an optional dot (e.g., [2-9]\.?[0-9]?[0-9]?),
; as they may be loosely matched and captured as `base_python`.
;
; For example, `molecule-py3.12-2.20`,
; In this case, simply providing `base_python` is not sufficient to resolve all issues.
; You also need to set `ignore_base_python_conflict = true` to skip the
; `validate_base_python` function during the `base_python` post-processing step.
envlist =
    molecule-py3.9-{2.10, 2.11, 2.12, 2.13, 2.14, 2.15}
ignore_base_python_conflict = true
toxworkdir = {toxinidir}/../../.tox

[testenv]
changedir = {toxinidir}/../../
; Only install the dependencies of the role repository;
; do not build or install the role itself as a package.
package = deps-only
; Use the `dependency-groups` in pyproject.toml generated from
; the pixi.toml `feature` as dependencies.
dependency_groups =
    2.15: core215
    2.14: core214
    2.13: core213
    2.12: core212
    2.11: core211
    2.10: core210
; Allow to run the `molecule` command for testing.
allowlist_externals = molecule
; By default, test the default scenario.
commands = molecule {env:MOLECULE_OPTIONS:} test --scenario-name {env:MOLECULE_SCENARIO_NAME:default}
; The environment variable `MOLECULE_GLOB` is used to discover Molecule test files
; The environment variables `XDG_CACHE_HOME` and `ANSIBLE_HOME` are used to isolate Molecule test files.
; The environment variable `ANSIBLE_ROLES_PATH` is used to resolve the issue of finding role projects.
;   Typically, `ansible_compat` will link the role symbol to the Ansible home roles dir.
setenv =
    ; https://forum.ansible.com/t/unable-to-install-collection-from-new-galaxy/1238/3
    2.10,2.11: ANSIBLE_CONFIG = {toxinidir}/../../molecule/ansible.old-galaxy.cfg

    2.15: MOLECULE_GLOB = {toxinidir}/../../molecule/core215/*/molecule.yml
    2.14: MOLECULE_GLOB = {toxinidir}/../../molecule/core214/*/molecule.yml
    2.13: MOLECULE_GLOB = {toxinidir}/../../molecule/core213/*/molecule.yml
    2.12: MOLECULE_GLOB = {toxinidir}/../../molecule/core212/*/molecule.yml
    2.11: MOLECULE_GLOB = {toxinidir}/../../molecule/core211/*/molecule.yml
    2.10: MOLECULE_GLOB = {toxinidir}/../../molecule/core210/*/molecule.yml

    2.15: XDG_CACHE_HOME = {toxinidir}/../../molecule/core215/.cache
    2.14: XDG_CACHE_HOME = {toxinidir}/../../molecule/core214/.cache
    2.13: XDG_CACHE_HOME = {toxinidir}/../../molecule/core213/.cache
    2.12: XDG_CACHE_HOME = {toxinidir}/../../molecule/core212/.cache
    2.11: XDG_CACHE_HOME = {toxinidir}/../../molecule/core211/.cache
    2.10: XDG_CACHE_HOME = {toxinidir}/../../molecule/core210/.cache

    2.15: ANSIBLE_HOME = {toxinidir}/../../molecule/core215/.ansible
    2.14: ANSIBLE_HOME = {toxinidir}/../../molecule/core214/.ansible
    2.13: ANSIBLE_HOME = {toxinidir}/../../molecule/core213/.ansible
    2.12: ANSIBLE_HOME = {toxinidir}/../../molecule/core212/.ansible
    2.11: ANSIBLE_HOME = {toxinidir}/../../molecule/core211/.ansible
    2.10: ANSIBLE_HOME = {toxinidir}/../../molecule/core210/.ansible

    2.15: ANSIBLE_ROLES_PATH = {toxinidir}/../../molecule/core215/.ansible/roles
    2.14: ANSIBLE_ROLES_PATH = {toxinidir}/../../molecule/core214/.ansible/roles
    2.13: ANSIBLE_ROLES_PATH = {toxinidir}/../../molecule/core213/.ansible/roles
    2.12: ANSIBLE_ROLES_PATH = {toxinidir}/../../molecule/core212/.ansible/roles
    2.11: ANSIBLE_ROLES_PATH = {toxinidir}/../../molecule/core211/.ansible/roles
    2.10: ANSIBLE_ROLES_PATH = {toxinidir}/../../molecule/core210/.ansible/roles
