---
# ref: [[#role_name_check|Go to molecule/README.md#role_name_check]]
role_name_check: 1

dependency:
  name: galaxy
  options:
    requirements-file: ${MOLECULE_SCENARIO_DIRECTORY}/requirements.yml

driver:
  # ref: [[#driver_default|Go to molecule/README.md#driver_default]]
  name: delegated
  options:
    managed: false
    ansible_connection_options:
      ansible_connection: local

platforms:
  - name: instance

provisioner:
  name: ansible
  inventory:
    hosts:
      all:
        hosts:
          instance:
            ansible_connection: local
  playbooks:
    converge: converge.yml

scenario:
  name: default

verifier:
  name: ansible
