
[tox]
minversion = 3.25.1
; The role repository cannot be packaged as a Python package.
skipsdist = true
; For environments with multiple FACTORS in their names,
; avoid using factors that are purely numeric with a dot (e.g., [23]\.[0-9]+),
; as they will be strictly matched and captured as `base_python`.
; Also avoid factors that start with py followed by numbers with
; an optional dot (e.g., [2-9]\.?[0-9]?[0-9]?),
; as they may be loosely matched and captured as `base_python`.
;
; For example, `molecule-py3.12-2.20`,
; In this case, simply providing `base_python` is not sufficient to resolve all issues.
; You also need to set `ignore_base_python_conflict = true` to skip the
; `validate_base_python` function during the `base_python` post-processing step.
envlist =
    molecule-py3.5-{2.9, 2.10, 2.11}
ignore_base_python_conflict = true
toxworkdir = {toxinidir}/../../.tox

[testenv]
changedir = {toxinidir}/../../
; Only install the dependencies of the role repository;
; do not build or install the role itself as a package.
package = deps-only
deps =
    2.11: -r{toxinidir}/requirements.core211.txt
    2.10: -r{toxinidir}/requirements.core210.txt
    2.9: -r{toxinidir}/requirements.core29.txt
; Allow to run the `molecule` command for testing.
allowlist_externals =
    bash
    molecule
; Check if the scenario should be skipped before running molecule
commands_pre =
    bash {toxinidir}/run-molecule-test.sh --check-only
    ; fix ANSIBLE_ROLES_PATH not work in py35
    python {toxinidir}/link-role-to-molecule-ephemeral-directory.py
; By default, test the default scenario.
commands = molecule {env:MOLECULE_OPTIONS:} test --scenario-name {env:MOLECULE_SCENARIO_NAME:default}
; The environment variable `MOLECULE_GLOB` is used to discover Molecule test files
; The environment variables `XDG_CACHE_HOME` and `ANSIBLE_HOME` are used to isolate Molecule test files.
; The environment variable `ANSIBLE_ROLES_PATH` is used to resolve the issue of finding role projects.
;   Typically, `ansible_compat` will link the role symbol to the Ansible home roles dir.
setenv =
    ; https://forum.ansible.com/t/unable-to-install-collection-from-new-galaxy/1238/3
    2.9,2.10,2.11: ANSIBLE_CONFIG = {toxinidir}/../../molecule/ansible.old-galaxy.cfg

    2.11: MOLECULE_GLOB = {toxinidir}/../../molecule/core211/*/molecule.yml
    2.10: MOLECULE_GLOB = {toxinidir}/../../molecule/core210/*/molecule.yml
    2.9: MOLECULE_GLOB = {toxinidir}/../../molecule/core29/*/molecule.yml

    2.11: XDG_CACHE_HOME = {toxinidir}/../../molecule/core211/.cache
    2.10: XDG_CACHE_HOME = {toxinidir}/../../molecule/core210/.cache
    2.9: XDG_CACHE_HOME = {toxinidir}/../../molecule/core29/.cache

    2.11: ANSIBLE_HOME = {toxinidir}/../../molecule/core211/.ansible
    2.10: ANSIBLE_HOME = {toxinidir}/../../molecule/core210/.ansible
    2.9: ANSIBLE_HOME = {toxinidir}/../../molecule/core29/.ansible

    2.11: ANSIBLE_ROLES_PATH = {toxinidir}/../../molecule/core211/.ansible/roles
    2.10: ANSIBLE_ROLES_PATH = {toxinidir}/../../molecule/core210/.ansible/roles
    2.9: ANSIBLE_ROLES_PATH = {toxinidir}/../../molecule/core29/.ansible/roles

    ; python 3.5 uses molecule 3.0.2.1 not support docker driver
    2.10: SKIP_MOLECULE_SCENARIO = docker
    2.11: SKIP_MOLECULE_SCENARIO = docker
    2.9: SKIP_MOLECULE_SCENARIO = docker

passenv =
    MOLECULE_SCENARIO_NAME
