FROM geerlingguy/docker-debian10-ansible

RUN sed -i 's|deb.debian.org|archive.debian.org|g' /etc/apt/sources.list && \
    sed -i '/security.debian.org/d' /etc/apt/sources.list && \
    echo 'Acquire::Check-Valid-Until "false";' > /etc/apt/apt.conf.d/99no-check-valid

RUN export DEBIAN_FRONTEND=noninteractive \
    && apt-get update \
    && apt-get install -y python3 sudo bash ca-certificates iproute2 python3-apt aptitude rsync \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
