---
# ref: [[#role_name_check|Go to molecule/README.md#role_name_check]]
role_name_check: 1

dependency:
  name: galaxy
  options:
    requirements-file: ${MOLECULE_SCENARIO_DIRECTORY}/requirements.yml

driver:
  name: default
  options:
    managed: false
    ansible_connection_options:
      ansible_connection: local

platforms:
  - name: local

provisioner:
  name: ansible
  inventory:
    hosts:
      all:
        hosts:
          local:
            ansible_connection: local
            ansible_become_password: ${MACOS_TEST_BECOME_PASSWORD}
  playbooks:
    converge: converge.yml

scenario:
  name: default-macos-latest

verifier:
  name: ansible
