#!/usr/bin/env python3
"""Generate pyproject.toml from pixi feature dependencies."""

from __future__ import annotations

import argparse
import pathlib
import tomllib


PROJECT_ROOT = pathlib.Path(__file__).resolve().parent.parent
DEFAULT_PIXI = PROJECT_ROOT / "pixi.toml"
DEFAULT_PYPROJECT = PROJECT_ROOT / "pyproject.toml"
FEATURE_PREFIX = "ansible-core-"


def normalize_version_spec(version: str) -> str:
    return ",".join(part.strip() for part in version.split(","))


def normalize_requirement(name: str, spec: object) -> str:
    if isinstance(spec, str):
        return name if spec == "*" else f"{name}{normalize_version_spec(spec)}"

    if not isinstance(spec, dict):
        raise TypeError(f"Unsupported dependency spec for {name!r}: {spec!r}")

    extras = spec.get("extras", [])
    version = spec.get("version", "*")

    if extras:
        extras_part = ",".join(extras)
        package_name = f"{name}[{extras_part}]"
    else:
        package_name = name

    if version == "*":
        return package_name

    return f"{package_name}{normalize_version_spec(version)}"


def feature_name_to_code_name(feature_name: str) -> str:
    if not feature_name.startswith(FEATURE_PREFIX):
        return feature_name

    version = feature_name.removeprefix(FEATURE_PREFIX)
    major, minor = version.split("-", maxsplit=1)
    return f"core{major}{minor}"


def collect_dependency_groups(pixi_data: dict) -> dict[str, list[str]]:
    features = pixi_data.get("feature", {})
    groups: dict[str, list[str]] = {}

    for current_feature_name, feature_config in features.items():
        pypi_dependencies = feature_config.get("pypi-dependencies")
        if not pypi_dependencies:
            continue

        groups[feature_name_to_code_name(current_feature_name)] = [
            normalize_requirement(dependency_name, dependency_spec)
            for dependency_name, dependency_spec in pypi_dependencies.items()
        ]

    return groups


def render_pyproject(groups: dict[str, list[str]]) -> str:
    lines = [
        "# THIS FILE IS GENERATED BY scripts/generate_tox_deps.py",
        "# DO NOT EDIT IT MANUALLY",
        "# DO NOT COMMIT IT TO GIT",
        "",
        "[project]",
        'name = "ansible-role-cloudflare-configured"',
        'version = "0.0.0"',
        'requires-python = ">=3.8"',
        "dependencies = []",
        "",
        "[dependency-groups]",
    ]

    for group_name, requirements in groups.items():
        lines.append(f'{group_name} = [')
        for requirement in requirements:
            lines.append(f'  "{requirement}",')
        lines.append("]")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def write_pyproject(groups: dict[str, list[str]], output_path: pathlib.Path) -> pathlib.Path:
    resolved_output_path = output_path if output_path.is_absolute() else PROJECT_ROOT / output_path
    resolved_output_path.parent.mkdir(parents=True, exist_ok=True)
    resolved_output_path.write_text(render_pyproject(groups), encoding="utf-8")
    return resolved_output_path


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate pyproject.toml from pixi feature dependencies.",
    )
    parser.add_argument(
        "--pixi",
        type=pathlib.Path,
        default=DEFAULT_PIXI,
        help=f"Path to pixi.toml (default: {DEFAULT_PIXI})",
    )
    parser.add_argument(
        "--pyproject-output",
        type=pathlib.Path,
        default=DEFAULT_PYPROJECT,
        help=f"Path to generated pyproject.toml (default: {DEFAULT_PYPROJECT})",
    )
    args = parser.parse_args()

    with args.pixi.open("rb") as handle:
        pixi_data = tomllib.load(handle)

    output_path = write_pyproject(collect_dependency_groups(pixi_data), args.pyproject_output)
    print(output_path.relative_to(PROJECT_ROOT))

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
