
[tox]
minversion = 4.52.1
; The role repository cannot be packaged as a Python package.
skipsdist = true
; For environments with multiple FACTORS in their names,
; avoid using factors that are purely numeric with a dot (e.g., [23]\.[0-9]+),
; as they will be strictly matched and captured as `base_python`.
; Also avoid factors that start with py followed by numbers with
; an optional dot (e.g., [2-9]\.?[0-9]?[0-9]?),
; as they may be loosely matched and captured as `base_python`.
;
; For example, `molecule-py3.12-2.20`,
; In this case, simply providing `base_python` is not sufficient to resolve all issues.
; You also need to set `ignore_base_python_conflict = true` to skip the
; `validate_base_python` function during the `base_python` post-processing step.
envlist =
    molecule-py3.14-{2.20}
ignore_base_python_conflict = true
toxworkdir = {toxinidir}/../../.tox

[testenv]
changedir = {toxinidir}/../../
; Only install the dependencies of the role repository;
; do not build or install the role itself as a package.
package = deps-only
; Use the `dependency-groups` in pyproject.toml generated from
; the pixi.toml `feature` as dependencies.
dependency_groups =
    2.20: core220
; Allow to run the `molecule` command for testing.
allowlist_externals = molecule
; Pass environment variables to the test environment.
passenv =
    WINDOWS_TEST_HOST
    WINDOWS_TEST_PORT
    WINDOWS_TEST_USER
    WINDOWS_TEST_PASSWORD
    WINDOWS_TEST_TRANSPORT
    WINDOWS_TEST_SCHEME
; By default, test the default scenario.
commands = molecule {env:MOLECULE_OPTIONS:} test --scenario-name {env:MOLECULE_SCENARIO_NAME:default}
; The environment variable `MOLECULE_GLOB` is used to discover Molecule test files
; The environment variables `XDG_CACHE_HOME` and `ANSIBLE_HOME` are used to isolate Molecule test files.
; The environment variable `ANSIBLE_ROLES_PATH` is used to resolve the issue of finding role projects.
;   Typically, `ansible_compat` will link the role symbol to the Ansible home roles dir.
setenv =
    2.20: MOLECULE_GLOB = {toxinidir}/../../molecule/core220/*/molecule.yml

    2.20: XDG_CACHE_HOME = {toxinidir}/../../molecule/core220/.cache

    2.20: ANSIBLE_HOME = {toxinidir}/../../molecule/core220/.ansible

    2.20: ANSIBLE_ROLES_PATH = {toxinidir}/../../molecule/core220/.ansible/roles
