
[tox]
minversion = 4.52.1
; The role repository cannot be packaged as a Python package.
skipsdist = true
; For environments with multiple FACTORS in their names,
; avoid using factors that are purely numeric with a dot (e.g., [23]\.[0-9]+),
; as they will be strictly matched and captured as `base_python`.
; Also avoid factors that start with py followed by numbers with
; an optional dot (e.g., [2-9]\.?[0-9]?[0-9]?),
; as they may be loosely matched and captured as `base_python`.
;
; For example, `molecule-py3.12-2.20`,
; In this case, simply providing `base_python` is not sufficient to resolve all issues.
; You also need to set `ignore_base_python_conflict = true` to skip the
; `validate_base_python` function during the `base_python` post-processing step.
envlist =
    molecule-py3.12-{2.16, 2.17, 2.18, 2.19, 2.20}
ignore_base_python_conflict = true
toxworkdir = {toxinidir}/../../.tox

[testenv]
changedir = {toxinidir}/../../
; Only install the dependencies of the role repository;
; do not build or install the role itself as a package.
package = deps-only
; Use the `dependency-groups` in pyproject.toml generated from
; the pixi.toml `feature` as dependencies.
dependency_groups =
    2.20: core220
    2.19: core219
    2.18: core218
    2.17: core217
    2.16: core216
; Allow to run the `molecule` command for testing.
allowlist_externals = molecule
; By default, test the default scenario.
commands = molecule {env:MOLECULE_OPTIONS:} test --scenario-name {env:MOLECULE_SCENARIO_NAME:default}
; The environment variable `MOLECULE_GLOB` is used to discover Molecule test files
; The environment variables `XDG_CACHE_HOME` and `ANSIBLE_HOME` are used to isolate Molecule test files.
; The environment variable `ANSIBLE_ROLES_PATH` is used to resolve the issue of finding role projects.
;   Typically, `ansible_compat` will link the role symbol to the Ansible home roles dir.
setenv =
    2.20: MOLECULE_GLOB = {toxinidir}/../../molecule/core220/*/molecule.yml
    2.19: MOLECULE_GLOB = {toxinidir}/../../molecule/core219/*/molecule.yml
    2.18: MOLECULE_GLOB = {toxinidir}/../../molecule/core218/*/molecule.yml
    2.17: MOLECULE_GLOB = {toxinidir}/../../molecule/core217/*/molecule.yml
    2.16: MOLECULE_GLOB = {toxinidir}/../../molecule/core216/*/molecule.yml

    2.20: XDG_CACHE_HOME = {toxinidir}/../../molecule/core220/.cache
    2.19: XDG_CACHE_HOME = {toxinidir}/../../molecule/core219/.cache
    2.18: XDG_CACHE_HOME = {toxinidir}/../../molecule/core218/.cache
    2.17: XDG_CACHE_HOME = {toxinidir}/../../molecule/core217/.cache
    2.16: XDG_CACHE_HOME = {toxinidir}/../../molecule/core216/.cache

    2.20: ANSIBLE_HOME = {toxinidir}/../../molecule/core220/.ansible
    2.19: ANSIBLE_HOME = {toxinidir}/../../molecule/core219/.ansible
    2.18: ANSIBLE_HOME = {toxinidir}/../../molecule/core218/.ansible
    2.17: ANSIBLE_HOME = {toxinidir}/../../molecule/core217/.ansible
    2.16: ANSIBLE_HOME = {toxinidir}/../../molecule/core216/.ansible

    2.20: ANSIBLE_ROLES_PATH = {toxinidir}/../../molecule/core220/.ansible/roles
    2.19: ANSIBLE_ROLES_PATH = {toxinidir}/../../molecule/core219/.ansible/roles
    2.18: ANSIBLE_ROLES_PATH = {toxinidir}/../../molecule/core218/.ansible/roles
    2.17: ANSIBLE_ROLES_PATH = {toxinidir}/../../molecule/core217/.ansible/roles
    2.16: ANSIBLE_ROLES_PATH = {toxinidir}/../../molecule/core216/.ansible/roles
