---
collections:
  # fix docker module too new or cant find
  # when py36/37 + core 2.9 + molecule 3.6.1 + molecule-docker 1.1.0:
  # molecule-docker require_collection "community.docker": "1.9.1",
  # but ansible-compat installed too newest version.
  # ansible 2.9 need community.docker < 3.0.0
  # see https://github.com/ansible-collections/community.docker/issues/477
  - name: community.docker
    version: "<3.0.0"
roles: []
